version: '3.9'

services:
  mysql:
    container_name: mysql8
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ~/docker-volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=blessing
      - MYSQL_DATABASE=church
    tty: true
    stdin_open: true
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    volumes:
      - ~/docker-volumes/jenkins:/var/jenkins_home