version: '3.9'

services:
  mssql:
    container_name: mssql
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    volumes:
      - ~/workspace/docker/docker-compose/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ~/volumes/mssql:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Khauhelo@1991
      - MSSQL_PID=Developer
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mssql
    tty: true
    stdin_open: true