version: '3.9'

services:
  mysql:
    container_name: mysql8
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ~/workspace/docker/docker-compose/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ~/volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=blessing
      - MYSQL_ROOT_HOST=%
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    tty: true
    stdin_open: true
    networks: 
      - spring-app
networks:
  spring-app:
    name: spring-app
    driver: bridge